server.port: 8222
spring.application.name: guli-gateway
spring.cloud.nacos.discovery.server-addr: 127.0.0.1:8848

spring.cloud.gateway.discovery.locator.enabled: true

spring.cloud.gateway.routes[0].id: guli-edu
spring.cloud.gateway.routes[0].uri: lb://guli-edu
spring.cloud.gateway.routes[0].predicates: Path=/edu/**

spring.cloud.gateway.routes[1].id: guli-ucenter
spring.cloud.gateway.routes[1].uri: lb://guli-ucenter
spring.cloud.gateway.routes[1].predicates: Path=/ucenter/**

spring.cloud.gateway.routes[2].id: guli-order
spring.cloud.gateway.routes[2].uri: lb://guli-order
spring.cloud.gateway.routes[2].predicates: Path=/orders/**

spring.cloud.gateway.routes[3].id: guli-statistics
spring.cloud.gateway.routes[3].uri: lb://guli-statistics
spring.cloud.gateway.routes[3].predicates: Path=/statistics/**